version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/data-engineering"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "data-engineering"
    commit-message:
      prefix: "data-eng"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
