services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: gamesdb
    environment:
      POSTGRES_DB: gamesdb
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gameuser -d gamesdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
