services:
  postgres-test:
    image: postgres:16-alpine
    container_name: gamesdb-test
    environment:
      POSTGRES_DB: gamesdb_test
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
    ports:
      - "5433:5432"  # Different port to not conflict with main DB
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
